// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/mojocn/base64Captcha"
	appuser2 "github.com/smilex/smilex-admin-gin/internal/biz/appuser"
	"github.com/smilex/smilex-admin-gin/internal/biz/auth"
	blacklist2 "github.com/smilex/smilex-admin-gin/internal/biz/blacklist"
	captcha2 "github.com/smilex/smilex-admin-gin/internal/biz/captcha"
	export2 "github.com/smilex/smilex-admin-gin/internal/biz/export"
	file2 "github.com/smilex/smilex-admin-gin/internal/biz/file"
	log2 "github.com/smilex/smilex-admin-gin/internal/biz/log"
	merchant2 "github.com/smilex/smilex-admin-gin/internal/biz/merchant"
	permission2 "github.com/smilex/smilex-admin-gin/internal/biz/permission"
	role2 "github.com/smilex/smilex-admin-gin/internal/biz/role"
	session2 "github.com/smilex/smilex-admin-gin/internal/biz/session"
	tenant2 "github.com/smilex/smilex-admin-gin/internal/biz/tenant"
	user2 "github.com/smilex/smilex-admin-gin/internal/biz/user"
	"github.com/smilex/smilex-admin-gin/internal/data"
	"github.com/smilex/smilex-admin-gin/internal/data/appuser"
	"github.com/smilex/smilex-admin-gin/internal/data/blacklist"
	"github.com/smilex/smilex-admin-gin/internal/data/captcha"
	"github.com/smilex/smilex-admin-gin/internal/data/export"
	"github.com/smilex/smilex-admin-gin/internal/data/file"
	"github.com/smilex/smilex-admin-gin/internal/data/log"
	"github.com/smilex/smilex-admin-gin/internal/data/merchant"
	"github.com/smilex/smilex-admin-gin/internal/data/permission"
	"github.com/smilex/smilex-admin-gin/internal/data/role"
	"github.com/smilex/smilex-admin-gin/internal/data/session"
	"github.com/smilex/smilex-admin-gin/internal/data/tenant"
	"github.com/smilex/smilex-admin-gin/internal/data/user"
	"github.com/smilex/smilex-admin-gin/internal/server"
	appuser3 "github.com/smilex/smilex-admin-gin/internal/service/appuser"
	auth2 "github.com/smilex/smilex-admin-gin/internal/service/auth"
	blacklist3 "github.com/smilex/smilex-admin-gin/internal/service/blacklist"
	export3 "github.com/smilex/smilex-admin-gin/internal/service/export"
	file3 "github.com/smilex/smilex-admin-gin/internal/service/file"
	log3 "github.com/smilex/smilex-admin-gin/internal/service/log"
	merchant3 "github.com/smilex/smilex-admin-gin/internal/service/merchant"
	permission3 "github.com/smilex/smilex-admin-gin/internal/service/permission"
	role3 "github.com/smilex/smilex-admin-gin/internal/service/role"
	session3 "github.com/smilex/smilex-admin-gin/internal/service/session"
	tenant3 "github.com/smilex/smilex-admin-gin/internal/service/tenant"
	user3 "github.com/smilex/smilex-admin-gin/internal/service/user"
)

// Injectors from wire.go:

// wireApp 由 wire 生成
func wireApp() (*server.HTTPServer, func(), error) {
	bootstrap, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	repo := user.NewRepo(dataData)
	roleRepo := role.NewRepo(dataData)
	permissionRepo := permission.NewRepo(dataData)
	tokenIssuer := data.NewJWTIssuer(bootstrap)
	client, cleanup2, err := data.NewRedisClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	store := captcha.NewStore(client)
	usecase := captcha2.NewUsecase(bootstrap, store)
	sessionRepo := session.NewRepo(client)
	sessionUsecase := session2.NewUsecase(sessionRepo, bootstrap)
	authUsecase := auth.NewUsecase(repo, roleRepo, permissionRepo, tokenIssuer, usecase, sessionUsecase)
	service := auth2.NewService(authUsecase, usecase)
	userUsecase := user2.NewUsecase(repo, sessionUsecase)
	userService := user3.NewService(userUsecase)
	roleUsecase := role2.NewUsecase(roleRepo)
	roleService := role3.NewService(roleUsecase)
	permissionUsecase := permission2.NewUsecase(permissionRepo)
	permissionService := permission3.NewService(permissionUsecase)
	sessionService := session3.NewService(sessionUsecase)
	logRepo, cleanup3, err := log.NewRepo(dataData, bootstrap)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	logUsecase := log2.NewUsecase(logRepo, bootstrap)
	logService := log3.NewService(logUsecase)
	fileRepo := file.NewRepo(dataData)
	storageManager, err := file.NewStorageManager(bootstrap)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fileUsecase := file2.NewUsecase(fileRepo, storageManager, bootstrap)
	fileService := file3.NewService(fileUsecase)
	exportRepo := export.NewRepo(dataData)
	userExporter := export2.NewUserExporter(repo, bootstrap)
	loginLogExporter := export2.NewLoginLogExporter(logRepo, bootstrap)
	opLogExporter := export2.NewOpLogExporter(logRepo, bootstrap)
	registry := export2.NewRegistry(userExporter, loginLogExporter, opLogExporter)
	worker, cleanup4, err := export.NewWorker(dataData, bootstrap, registry, storageManager, exportRepo)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	exportUsecase := export2.NewUsecase(exportRepo, registry, worker, storageManager, bootstrap)
	exportService := export3.NewService(exportUsecase)
	blacklistRepo := blacklist.NewRepo(dataData, client)
	blacklistUsecase := blacklist2.NewUsecase(blacklistRepo, blacklistRepo)
	blacklistService := blacklist3.NewService(blacklistUsecase)
	merchantRepo := merchant.NewRepo(dataData)
	apiLogRepo, cleanup5, err := merchant.NewAPILogRepo(dataData, bootstrap)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	merchantUsecase := merchant2.NewUsecase(merchantRepo, apiLogRepo)
	merchantService := merchant3.NewService(merchantUsecase)
	tenantRepo := tenant.NewRepo(dataData)
	tenantUsecase := tenant2.NewUsecase(tenantRepo)
	tenantService := tenant3.NewService(tenantUsecase)
	appuserRepo := appuser.NewRepo(dataData)
	appuserTokenIssuer := data.NewAppTokenIssuer(bootstrap)
	appuserUsecase := appuser2.NewUsecase(appuserRepo, appuserTokenIssuer)
	appuserService := appuser3.NewService(appuserUsecase)
	httpServer := server.NewHTTPServer(bootstrap, service, userService, roleService, permissionService, sessionService, logService, fileService, exportService, blacklistService, merchantService, merchantUsecase, tenantService, appuserService, appuserUsecase, appuserTokenIssuer, client)
	return httpServer, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var bizSet = wire.NewSet(user2.NewUsecase, role2.NewUsecase, permission2.NewUsecase, captcha2.NewUsecase, session2.NewUsecase, log2.NewUsecase, file2.NewUsecase, blacklist2.NewUsecase, merchant2.NewUsecase, tenant2.NewUsecase, appuser2.NewUsecase, export2.NewUsecase, export2.NewRegistry, export2.NewUserExporter, export2.NewLoginLogExporter, export2.NewOpLogExporter, auth.NewUsecase, wire.Bind(new(auth.CaptchaVerifier), new(*captcha2.Usecase)), wire.Bind(new(auth.SessionManager), new(*session2.Usecase)), wire.Bind(new(user2.SessionRevoker), new(*session2.Usecase)))

var dataRepoSet = wire.NewSet(data.NewData, data.NewRedisClient, data.NewJWTIssuer, data.NewAppTokenIssuer, user.NewRepo, role.NewRepo, permission.NewRepo, session.NewRepo, log.NewRepo, file.NewRepo, file.NewStorageManager, blacklist.NewRepo, merchant.NewRepo, merchant.NewAPILogRepo, tenant.NewRepo, appuser.NewRepo, captcha.NewStore, export.NewRepo, export.NewWorker, wire.Bind(new(base64Captcha.Store), new(*captcha.Store)), wire.Bind(new(auth.UserStore), new(user2.Repo)), wire.Bind(new(auth.RoleNameReader), new(role2.Repo)), wire.Bind(new(auth.PermissionReader), new(permission2.Repo)), wire.Bind(new(log2.Repo), new(*log.Repo)), wire.Bind(new(blacklist2.Repo), new(*blacklist.Repo)), wire.Bind(new(blacklist2.LoginProtector), new(*blacklist.Repo)), wire.Bind(new(export2.Enqueuer), new(*export.Worker)))

var serviceSet = wire.NewSet(auth2.NewService, user3.NewService, role3.NewService, permission3.NewService, session3.NewService, log3.NewService, file3.NewService, blacklist3.NewService, export3.NewService, merchant3.NewService, tenant3.NewService, appuser3.NewService)

var providerSet = wire.NewSet(bizSet, dataRepoSet, serviceSet, ProvideConfig, server.NewHTTPServer)
