// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	admission2 "github.com/smilex/smilex-admin-gin/internal/biz/admission"
	appuser2 "github.com/smilex/smilex-admin-gin/internal/biz/appuser"
	auth2 "github.com/smilex/smilex-admin-gin/internal/biz/auth"
	blacklist2 "github.com/smilex/smilex-admin-gin/internal/biz/blacklist"
	device2 "github.com/smilex/smilex-admin-gin/internal/biz/device"
	devmodel2 "github.com/smilex/smilex-admin-gin/internal/biz/devmodel"
	export2 "github.com/smilex/smilex-admin-gin/internal/biz/export"
	file2 "github.com/smilex/smilex-admin-gin/internal/biz/file"
	log2 "github.com/smilex/smilex-admin-gin/internal/biz/log"
	permission2 "github.com/smilex/smilex-admin-gin/internal/biz/permission"
	role2 "github.com/smilex/smilex-admin-gin/internal/biz/role"
	tenant2 "github.com/smilex/smilex-admin-gin/internal/biz/tenant"
	"github.com/smilex/smilex-admin-gin/internal/data"
	"github.com/smilex/smilex-admin-gin/internal/data/admission"
	"github.com/smilex/smilex-admin-gin/internal/data/appuser"
	"github.com/smilex/smilex-admin-gin/internal/data/auth"
	"github.com/smilex/smilex-admin-gin/internal/data/blacklist"
	"github.com/smilex/smilex-admin-gin/internal/data/device"
	"github.com/smilex/smilex-admin-gin/internal/data/devmodel"
	"github.com/smilex/smilex-admin-gin/internal/data/export"
	"github.com/smilex/smilex-admin-gin/internal/data/file"
	"github.com/smilex/smilex-admin-gin/internal/data/log"
	"github.com/smilex/smilex-admin-gin/internal/data/permission"
	"github.com/smilex/smilex-admin-gin/internal/data/platform"
	"github.com/smilex/smilex-admin-gin/internal/data/role"
	"github.com/smilex/smilex-admin-gin/internal/data/tenant"
	"github.com/smilex/smilex-admin-gin/internal/server"
	admission3 "github.com/smilex/smilex-admin-gin/internal/service/admission"
	appuser3 "github.com/smilex/smilex-admin-gin/internal/service/appuser"
	auth3 "github.com/smilex/smilex-admin-gin/internal/service/auth"
	blacklist3 "github.com/smilex/smilex-admin-gin/internal/service/blacklist"
	device3 "github.com/smilex/smilex-admin-gin/internal/service/device"
	devmodel3 "github.com/smilex/smilex-admin-gin/internal/service/devmodel"
	export3 "github.com/smilex/smilex-admin-gin/internal/service/export"
	file3 "github.com/smilex/smilex-admin-gin/internal/service/file"
	log3 "github.com/smilex/smilex-admin-gin/internal/service/log"
	permission3 "github.com/smilex/smilex-admin-gin/internal/service/permission"
	role3 "github.com/smilex/smilex-admin-gin/internal/service/role"
	tenant3 "github.com/smilex/smilex-admin-gin/internal/service/tenant"
)

// Injectors from wire.go:

// wireApp 由 wire 生成
func wireApp() (*server.HTTPServer, func(), error) {
	bootstrap, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	identityClient := platform.NewIdentityClient(bootstrap)
	identityAdapter := auth.NewIdentityAdapter(identityClient)
	dataData, cleanup, err := data.NewData(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	repo := admission.NewRepo(dataData)
	client := platform.NewOpenAPIClient(bootstrap)
	platformGateway := admission.NewPlatformGateway(client)
	redisClient, cleanup2, err := data.NewRedisClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rbacCache := data.NewRBACCache(redisClient, bootstrap)
	usecase := admission2.NewUsecase(repo, platformGateway, rbacCache, bootstrap)
	permissionRepo := permission.NewRepo(dataData)
	roleRepo := role.NewRepo(dataData)
	authUsecase := auth2.NewUsecase(identityAdapter, usecase, permissionRepo, roleRepo)
	service := auth3.NewService(authUsecase)
	admissionService := admission3.NewService(usecase)
	roleUsecase := role2.NewUsecase(roleRepo, rbacCache)
	roleService := role3.NewService(roleUsecase)
	permissionUsecase := permission2.NewUsecase(permissionRepo)
	permissionService := permission3.NewService(permissionUsecase)
	logRepo, cleanup3, err := log.NewRepo(dataData, bootstrap)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	logUsecase := log2.NewUsecase(logRepo, bootstrap)
	logService := log3.NewService(logUsecase)
	fileRepo := file.NewRepo(dataData)
	storageClient := platform.NewStorageClient(bootstrap)
	storageManager, err := file.NewStorageManager(bootstrap, storageClient)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fileUsecase := file2.NewUsecase(fileRepo, storageManager, bootstrap)
	fileService := file3.NewService(fileUsecase)
	exportRepo := export.NewRepo(dataData)
	userExporter := export2.NewUserExporter(repo, bootstrap)
	opLogExporter := export2.NewOpLogExporter(logRepo, bootstrap)
	registry := export2.NewRegistry(userExporter, opLogExporter)
	worker, cleanup4, err := export.NewWorker(dataData, bootstrap, registry, storageManager, exportRepo)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	exportUsecase := export2.NewUsecase(exportRepo, registry, worker, storageManager, bootstrap)
	exportService := export3.NewService(exportUsecase)
	blacklistRepo := blacklist.NewRepo(dataData, redisClient)
	blacklistUsecase := blacklist2.NewUsecase(blacklistRepo, blacklistRepo)
	blacklistService := blacklist3.NewService(blacklistUsecase)
	tenantRepo := tenant.NewRepo(dataData)
	syncer := tenant.NewSyncer(client)
	tenantUsecase := tenant2.NewUsecase(tenantRepo, syncer)
	tenantService := tenant3.NewService(tenantUsecase)
	appuserRepo := appuser.NewRepo(dataData)
	tokenIssuer := data.NewAppTokenIssuer(bootstrap)
	appuserUsecase := appuser2.NewUsecase(appuserRepo, tokenIssuer)
	appuserService := appuser3.NewService(appuserUsecase)
	gatewayAdapter := device.NewGatewayAdapter(client)
	tenantReader := tenant.NewTenantAvailability(dataData)
	deviceUsecase := device2.NewUsecase(gatewayAdapter, tenantReader)
	deviceService := device3.NewService(deviceUsecase)
	devmodelGatewayAdapter := devmodel.NewGatewayAdapter(client)
	devmodelUsecase := devmodel2.NewUsecase(devmodelGatewayAdapter)
	devmodelService := devmodel3.NewService(devmodelUsecase)
	httpServer := server.NewHTTPServer(bootstrap, service, admissionService, usecase, roleService, permissionService, logService, fileService, exportService, blacklistService, tenantService, appuserService, appuserUsecase, tokenIssuer, deviceService, devmodelService, rbacCache, redisClient)
	return httpServer, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var bizSet = wire.NewSet(admission2.NewUsecase, role2.NewUsecase, permission2.NewUsecase, log2.NewUsecase, file2.NewUsecase, blacklist2.NewUsecase, tenant2.NewUsecase, appuser2.NewUsecase, device2.NewUsecase, devmodel2.NewUsecase, export2.NewUsecase, export2.NewRegistry, export2.NewUserExporter, export2.NewOpLogExporter, auth2.NewUsecase, wire.Bind(new(auth2.AdmissionReader), new(*admission2.Usecase)))

var dataRepoSet = wire.NewSet(data.NewData, data.NewRedisClient, data.NewAppTokenIssuer, data.NewRBACCache, admission.NewRepo, role.NewRepo, permission.NewRepo, log.NewRepo, file.NewRepo, file.NewStorageManager, blacklist.NewRepo, tenant.NewRepo, appuser.NewRepo, export.NewRepo, export.NewWorker, platform.NewIdentityClient, platform.NewStorageClient, platform.NewOpenAPIClient, device.NewGatewayAdapter, devmodel.NewGatewayAdapter, tenant.NewSyncer, tenant.NewTenantAvailability, admission.NewPlatformGateway, auth.NewIdentityAdapter, wire.Bind(new(auth2.IdentitySource), new(*auth.IdentityAdapter)), wire.Bind(new(auth2.PermissionReader), new(permission2.Repo)), wire.Bind(new(auth2.RoleNameReader), new(role2.Repo)), wire.Bind(new(log2.Repo), new(*log.Repo)), wire.Bind(new(blacklist2.Repo), new(*blacklist.Repo)), wire.Bind(new(blacklist2.LoginProtector), new(*blacklist.Repo)), wire.Bind(new(export2.Enqueuer), new(*export.Worker)), wire.Bind(new(tenant2.PlatformSyncer), new(*tenant.Syncer)), wire.Bind(new(device2.Gateway), new(*device.GatewayAdapter)), wire.Bind(new(devmodel2.Gateway), new(*devmodel.GatewayAdapter)), wire.Bind(new(admission2.MemberGateway), new(*admission.PlatformGateway)), wire.Bind(new(admission2.DecisionCache), new(*data.RBACCache)), wire.Bind(new(role2.DecisionCache), new(*data.RBACCache)))

var serviceSet = wire.NewSet(auth3.NewService, admission3.NewService, role3.NewService, permission3.NewService, log3.NewService, file3.NewService, blacklist3.NewService, export3.NewService, tenant3.NewService, appuser3.NewService, device3.NewService, devmodel3.NewService)

var providerSet = wire.NewSet(bizSet, dataRepoSet, serviceSet, ProvideConfig, server.NewHTTPServer)
